### ISSUE TITLE
Failed to evaluate (400 bad request)

### ISSUE THREAD

**Issue by reteps** [unixpickle/safeval.pw#1]
Coming from your kahoot bot: 

URL: `
http://safeval.pw/eval?code=decode.call%28this%2C+%27kZ8CcJMEbgYs86YZ9Z602P5PCV3YC3NlQoWgDfdQ1dil86o6CNAE8588LsQr7gt46GPYDQG4nWaKIOL82HdmuOvaMmwS75QsXijF%27%29%3B+function+decode%28message%29+%7Bvar+offset+%3D+%281+%2A+39+%2A+%28%2892+%2B+71%29+%2B+%2878+%2B+79%29%29%29%3B+if+%28this.angular.isArray%28offset%29%29+%7Bconsole.log%28%22Offset+derived+as%3A+%7B%22%2C+offset%2C+%22%7D%22%29%3B%7Dreturn+_.replace%28message%2C+%2F.%2Fg%2C+function%28char%2C+position%29+%7Breturn+String.fromCharCode%28%28%28%28char.charCodeAt%280%29+%2A+position%29+%2B+offset%29+%25+77%29+%2B+48%29%3B%7D%29%3B%7D`

Code:
`decode.call(this, 'kZ8CcJMEbgYs86YZ9Z602P5PCV3YC3NlQoWgDfdQ1dil86o6CNAE8588LsQr7gt46GPYDQG4nWaKIOL82HdmuOvaMmwS75QsXijF'); function decode(message) {var offset = (1 * 39 * ((92 + 71) + (78 + 79))); if (this.angular.isArray(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
`

**Comment by unixpickle** [comment]
I am going to re-make this website to use headless Chromium, that way you can run the code in the context of an arbitrary webpage.

**Comment by unixpickle** [comment]
Should be fixed by commit 1158745534314a0e018d55ec1ea43952e4e864ea.
